### ISSUE TITLE
After clicks update button get error page

### ISSUE THREAD

**Issue by Irani96** [hmislk/hmis#9384]
Daily Return Show Differences. Then Click the update button Getting Error.
https://youtu.be/bh47Q_e5thA

**Comment by buddhika75** [comment]
### Issue is caused by the : `javax.ejb.AccessLocalException` Occurs on Production Server

**Description:**
The method `retireNonSettledOnlineBills()` in the `ChannelService` EJB causes the following error on the **production server**:

```
javax.ejb.AccessLocalException: Client not authorized for this invocation
```

This issue **does not occur** on staging or development servers.

**Steps Taken:**
1. Verified that the issue is limited to the production environment. The method works as expected on staging and development servers.
2. Updated the code in the development environment to temporarily bypass role-based security using `@PermitAll` as a shortcut. This ensured that the method could execute without errors, confirming the issue is related to security constraints.
3. Since direct testing on the production server is not feasible, we need to deploy the updated version to production to verify the fix.
4. Once time is available after achieving the current deadlines, we will replace the `@PermitAll` annotation with proper security role configuration to follow best practices.

**Next Steps:**
- Deploy the updated code to production and test.
- Investigate any discrepancies in role mapping, server security policies, or deployment descriptors that may exist between production and other environments.
- Apply a final security role-based configuration once time is available.

**Notes:**
This issue appears to be specific to the production server’s security or environment configuration. The temporary use of `@PermitAll` is intended as a stopgap measure and will be replaced with the appropriate role-based access controls once the the current tight deadlines are settled.
