### ISSUE TITLE
Net Cash Daily Return not tally Will All Cashier Summery Cash (Difference 6,678.00)

### ISSUE THREAD

**Issue by DeshaniPubudu** [hmislk/hmis#9423]
Net Cash Daily Return not tally Will All Cashier Summery Cash (Difference 6,678.00)

expalin:
When Doing Credit Company Payment,
1. Error was displayed when the settle bill of Mr. M L Bandaranaye - Using Cash (6428)
2. Secondly Cashier was settled another Patient's biil - Using Card (6678)
3. After that both patient bill displayed in same bill. 
4. Then after cashier cancel the that bill. 
5. 6678 Card Bill was not reduced from All Cashier Summary, Cashier Details, Cashier Summary.

![Image](https://github.com/user-attachments/assets/11b51ba9-c727-42e1-803b-071c2c1f23a9)

**Comment by buddhika75** [comment]
This error has happend due to an error in settling credit Bills. Now the wrong data needs cleaning. There is only one transaction is affected. It will be corrected by @DamithDeshan 
Now I have update the credit bill settling process for OPD Bills
It will make sure that the error will NOT happen in future.
Please try to settle credit bills (OPD Batch Bills and OPD Package Bills) under Finance > Payment Management > Credit Company > Settle OPD Credit Batch Bills & Settle OPD Package Credit Batch Bills
![image](https://github.com/user-attachments/assets/0bf6b126-a34f-4562-b1f2-ba8b18a5e998)

**Comment by buddhika75** [comment]
Please create some OPD Credit Bills.
Then settle the credit bills from Company Payments

Also do the same for OPD Package Bills
